# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tracker_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1046, 485)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 0, 3, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab_6)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_12 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.active_path_label = QtWidgets.QLabel(self.groupBox_12)
        self.active_path_label.setObjectName("active_path_label")
        self.gridLayout_22.addWidget(self.active_path_label, 5, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_12)
        self.label_20.setObjectName("label_20")
        self.gridLayout_22.addWidget(self.label_20, 5, 0, 1, 1)
        self.chooseProjectPath_b = QtWidgets.QPushButton(self.groupBox_12)
        self.chooseProjectPath_b.setObjectName("chooseProjectPath_b")
        self.gridLayout_22.addWidget(self.chooseProjectPath_b, 0, 0, 1, 2)
        self.gridLayout_11.addWidget(self.groupBox_12, 0, 0, 1, 2)
        self.groupBox_11 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cal3D_LW1 = QtWidgets.QListWidget(self.groupBox_11)
        self.cal3D_LW1.setObjectName("cal3D_LW1")
        self.verticalLayout_6.addWidget(self.cal3D_LW1)
        self.loadCal3D_b = QtWidgets.QPushButton(self.groupBox_11)
        self.loadCal3D_b.setObjectName("loadCal3D_b")
        self.verticalLayout_6.addWidget(self.loadCal3D_b)
        self.removeCal3D_b = QtWidgets.QPushButton(self.groupBox_11)
        self.removeCal3D_b.setObjectName("removeCal3D_b")
        self.verticalLayout_6.addWidget(self.removeCal3D_b)
        self.gridLayout_11.addWidget(self.groupBox_11, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 3, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.track_TE = QtWidgets.QTextBrowser(self.groupBox_4)
        self.track_TE.setMinimumSize(QtCore.QSize(200, 0))
        self.track_TE.setObjectName("track_TE")
        self.verticalLayout.addWidget(self.track_TE)
        self.gridLayout_5.addWidget(self.groupBox_4, 0, 2, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_20 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.groupBox_20)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_12.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_12.addWidget(self.label_13, 0, 2, 1, 1)
        self.start_l = QtWidgets.QLabel(self.frame_3)
        self.start_l.setObjectName("start_l")
        self.gridLayout_12.addWidget(self.start_l, 0, 1, 1, 1)
        self.end_l = QtWidgets.QLabel(self.frame_3)
        self.end_l.setObjectName("end_l")
        self.gridLayout_12.addWidget(self.end_l, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 1)
        self.trkTrack_B = QtWidgets.QPushButton(self.groupBox_20)
        self.trkTrack_B.setCheckable(True)
        self.trkTrack_B.setObjectName("trkTrack_B")
        self.gridLayout.addWidget(self.trkTrack_B, 5, 0, 1, 1)
        self.selectStartStop_b = QtWidgets.QPushButton(self.groupBox_20)
        self.selectStartStop_b.setObjectName("selectStartStop_b")
        self.gridLayout.addWidget(self.selectStartStop_b, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 6, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_20, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.trkPreview_B = QtWidgets.QPushButton(self.groupBox)
        self.trkPreview_B.setObjectName("trkPreview_B")
        self.gridLayout_9.addWidget(self.trkPreview_B, 2, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.groupBox)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.trkFramerate_LE = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trkFramerate_LE.sizePolicy().hasHeightForWidth())
        self.trkFramerate_LE.setSizePolicy(sizePolicy)
        self.trkFramerate_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.trkFramerate_LE.setObjectName("trkFramerate_LE")
        self.gridLayout_2.addWidget(self.trkFramerate_LE, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 1, 1, 1)
        self.gridLayout_9.addWidget(self.frame_4, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 5, 0, 1, 1)
        self.trkLoad_B = QtWidgets.QPushButton(self.groupBox)
        self.trkLoad_B.setObjectName("trkLoad_B")
        self.gridLayout_9.addWidget(self.trkLoad_B, 0, 0, 2, 1)
        self.pathLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLabel.sizePolicy().hasHeightForWidth())
        self.pathLabel.setSizePolicy(sizePolicy)
        self.pathLabel.setMaximumSize(QtCore.QSize(400, 16777215))
        self.pathLabel.setScaledContents(False)
        self.pathLabel.setWordWrap(True)
        self.pathLabel.setObjectName("pathLabel")
        self.gridLayout_9.addWidget(self.pathLabel, 6, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_19.setObjectName("groupBox_19")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_19)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.groupBox_21 = QtWidgets.QGroupBox(self.groupBox_19)
        self.groupBox_21.setEnabled(False)
        self.groupBox_21.setObjectName("groupBox_21")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.le_originy = QtWidgets.QLineEdit(self.groupBox_21)
        self.le_originy.setObjectName("le_originy")
        self.gridLayout_26.addWidget(self.le_originy, 1, 1, 1, 1)
        self.le_originx = QtWidgets.QLineEdit(self.groupBox_21)
        self.le_originx.setObjectName("le_originx")
        self.gridLayout_26.addWidget(self.le_originx, 1, 0, 1, 1)
        self.le_topx = QtWidgets.QLineEdit(self.groupBox_21)
        self.le_topx.setObjectName("le_topx")
        self.gridLayout_26.addWidget(self.le_topx, 1, 2, 1, 1)
        self.le_topy = QtWidgets.QLineEdit(self.groupBox_21)
        self.le_topy.setObjectName("le_topy")
        self.gridLayout_26.addWidget(self.le_topy, 1, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_21)
        self.label_18.setObjectName("label_18")
        self.gridLayout_26.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_21)
        self.label_19.setObjectName("label_19")
        self.gridLayout_26.addWidget(self.label_19, 0, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_21)
        self.label_21.setObjectName("label_21")
        self.gridLayout_26.addWidget(self.label_21, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_21)
        self.label_11.setToolTip("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_26.addWidget(self.label_11, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_21, 3, 0, 1, 1)
        self.rb_MOG = QtWidgets.QRadioButton(self.groupBox_19)
        self.rb_MOG.setChecked(False)
        self.rb_MOG.setObjectName("rb_MOG")
        self.gridLayout_17.addWidget(self.rb_MOG, 1, 0, 1, 1)
        self.rb_absolute = QtWidgets.QRadioButton(self.groupBox_19)
        self.rb_absolute.setChecked(True)
        self.rb_absolute.setObjectName("rb_absolute")
        self.gridLayout_17.addWidget(self.rb_absolute, 0, 0, 1, 1)
        self.blockRegion_CB = QtWidgets.QCheckBox(self.groupBox_19)
        self.blockRegion_CB.setChecked(False)
        self.blockRegion_CB.setObjectName("blockRegion_CB")
        self.gridLayout_17.addWidget(self.blockRegion_CB, 2, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_19, 0, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.medianFilterCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.medianFilterCheckbox.setObjectName("medianFilterCheckbox")
        self.gridLayout_4.addWidget(self.medianFilterCheckbox, 4, 0, 1, 1)
        self.kernelSlider = QtWidgets.QSlider(self.groupBox_2)
        self.kernelSlider.setMinimum(1)
        self.kernelSlider.setMaximum(25)
        self.kernelSlider.setOrientation(QtCore.Qt.Horizontal)
        self.kernelSlider.setObjectName("kernelSlider")
        self.gridLayout_4.addWidget(self.kernelSlider, 7, 1, 1, 1)
        self.kernelValueLabel = QtWidgets.QLabel(self.groupBox_2)
        self.kernelValueLabel.setObjectName("kernelValueLabel")
        self.gridLayout_4.addWidget(self.kernelValueLabel, 7, 2, 1, 1)
        self.erodeCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.erodeCheckbox.setObjectName("erodeCheckbox")
        self.gridLayout_4.addWidget(self.erodeCheckbox, 7, 0, 1, 1)
        self.dilateCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.dilateCheckbox.setObjectName("dilateCheckbox")
        self.gridLayout_4.addWidget(self.dilateCheckbox, 6, 0, 1, 1)
        self.contourLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contourLineEdit.sizePolicy().hasHeightForWidth())
        self.contourLineEdit.setSizePolicy(sizePolicy)
        self.contourLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.contourLineEdit.setObjectName("contourLineEdit")
        self.gridLayout_4.addWidget(self.contourLineEdit, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 7, 3, 1, 1)
        self.trkContour_B = QtWidgets.QPushButton(self.groupBox_2)
        self.trkContour_B.setObjectName("trkContour_B")
        self.gridLayout_4.addWidget(self.trkContour_B, 0, 1, 1, 2)
        self.gaussCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.gaussCheckBox.setObjectName("gaussCheckBox")
        self.gridLayout_4.addWidget(self.gaussCheckBox, 1, 0, 1, 1)
        self.gaussSlider = QtWidgets.QSlider(self.groupBox_2)
        self.gaussSlider.setProperty("value", 0)
        self.gaussSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gaussSlider.setInvertedControls(True)
        self.gaussSlider.setObjectName("gaussSlider")
        self.gridLayout_4.addWidget(self.gaussSlider, 1, 1, 1, 1)
        self.gaussValueLabel = QtWidgets.QLabel(self.groupBox_2)
        self.gaussValueLabel.setObjectName("gaussValueLabel")
        self.gridLayout_4.addWidget(self.gaussValueLabel, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 4, 3, 1, 1)
        self.medianSlider = QtWidgets.QSlider(self.groupBox_2)
        self.medianSlider.setOrientation(QtCore.Qt.Horizontal)
        self.medianSlider.setObjectName("medianSlider")
        self.gridLayout_4.addWidget(self.medianSlider, 4, 1, 1, 1)
        self.medianValueLabel = QtWidgets.QLabel(self.groupBox_2)
        self.medianValueLabel.setObjectName("medianValueLabel")
        self.gridLayout_4.addWidget(self.medianValueLabel, 4, 2, 1, 1)
        self.label_6.raise_()
        self.gaussCheckBox.raise_()
        self.medianFilterCheckbox.raise_()
        self.gaussSlider.raise_()
        self.gaussValueLabel.raise_()
        self.dilateCheckbox.raise_()
        self.erodeCheckbox.raise_()
        self.kernelSlider.raise_()
        self.kernelValueLabel.raise_()
        self.medianSlider.raise_()
        self.medianValueLabel.raise_()
        self.label_9.raise_()
        self.label.raise_()
        self.label_5.raise_()
        self.contourLineEdit.raise_()
        self.trkContour_B.raise_()
        self.gridLayout_8.addWidget(self.groupBox_2, 1, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pp_TV = QtWidgets.QTableView(self.groupBox_5)
        self.pp_TV.setMinimumSize(QtCore.QSize(300, 0))
        self.pp_TV.setObjectName("pp_TV")
        self.verticalLayout_2.addWidget(self.pp_TV)
        self.gridLayout_14.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_9.setEnabled(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.groupBox_9)
        self.widget_2.setEnabled(True)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_10 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_10)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.calView1_3D_select_B = QtWidgets.QPushButton(self.groupBox_10)
        self.calView1_3D_select_B.setObjectName("calView1_3D_select_B")
        self.verticalLayout_5.addWidget(self.calView1_3D_select_B)
        self.calView2_3D_select_B = QtWidgets.QPushButton(self.groupBox_10)
        self.calView2_3D_select_B.setObjectName("calView2_3D_select_B")
        self.verticalLayout_5.addWidget(self.calView2_3D_select_B)
        self.line_2 = QtWidgets.QFrame(self.groupBox_10)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.ppBlank_B = QtWidgets.QPushButton(self.groupBox_15)
        self.ppBlank_B.setObjectName("ppBlank_B")
        self.gridLayout_16.addWidget(self.ppBlank_B, 0, 1, 1, 1)
        self.ppUndo_B = QtWidgets.QPushButton(self.groupBox_15)
        self.ppUndo_B.setObjectName("ppUndo_B")
        self.gridLayout_16.addWidget(self.ppUndo_B, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem4, 2, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_15)
        self.gridLayout_10.addWidget(self.groupBox_10, 0, 3, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ppClearList_B = QtWidgets.QPushButton(self.groupBox_3)
        self.ppClearList_B.setObjectName("ppClearList_B")
        self.gridLayout_3.addWidget(self.ppClearList_B, 7, 0, 1, 2)
        self.label_34 = QtWidgets.QLabel(self.groupBox_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 0, 1, 1, 1)
        self.cal3D_LW2 = QtWidgets.QListWidget(self.groupBox_3)
        self.cal3D_LW2.setObjectName("cal3D_LW2")
        self.gridLayout_3.addWidget(self.cal3D_LW2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.csvList_LW = QtWidgets.QListWidget(self.groupBox_3)
        self.csvList_LW.setObjectName("csvList_LW")
        self.gridLayout_3.addWidget(self.csvList_LW, 1, 0, 2, 1)
        self.show2Dplot_B = QtWidgets.QCheckBox(self.groupBox_3)
        self.show2Dplot_B.setChecked(True)
        self.show2Dplot_B.setObjectName("show2Dplot_B")
        self.gridLayout_3.addWidget(self.show2Dplot_B, 3, 0, 1, 1)
        self.ppFileOpen_B = QtWidgets.QPushButton(self.groupBox_3)
        self.ppFileOpen_B.setObjectName("ppFileOpen_B")
        self.gridLayout_3.addWidget(self.ppFileOpen_B, 6, 0, 1, 2)
        self.gridLayout_10.addWidget(self.groupBox_3, 0, 0, 1, 3)
        self.groupBox_24 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_24.setObjectName("groupBox_24")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.groupBox_24)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.frame_2 = QtWidgets.QFrame(self.groupBox_24)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.addView_3D_b = QtWidgets.QPushButton(self.frame_2)
        self.addView_3D_b.setObjectName("addView_3D_b")
        self.gridLayout_34.addWidget(self.addView_3D_b, 2, 0, 1, 1)
        self.gridLayout_33.addWidget(self.frame_2, 1, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_24)
        self.label_33.setObjectName("label_33")
        self.gridLayout_33.addWidget(self.label_33, 0, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_24)
        self.label_32.setObjectName("label_32")
        self.gridLayout_33.addWidget(self.label_32, 0, 0, 1, 1)
        self.reconstruct3D_LW = QtWidgets.QListWidget(self.groupBox_24)
        self.reconstruct3D_LW.setObjectName("reconstruct3D_LW")
        self.gridLayout_33.addWidget(self.reconstruct3D_LW, 1, 0, 1, 1)
        self.clear_reconst3D_LW_b = QtWidgets.QPushButton(self.groupBox_24)
        self.clear_reconst3D_LW_b.setObjectName("clear_reconst3D_LW_b")
        self.gridLayout_33.addWidget(self.clear_reconst3D_LW_b, 2, 0, 1, 1)
        self.cleartracks3DLW_b = QtWidgets.QPushButton(self.groupBox_24)
        self.cleartracks3DLW_b.setObjectName("cleartracks3DLW_b")
        self.gridLayout_33.addWidget(self.cleartracks3DLW_b, 2, 2, 1, 1)
        self.reconstruct_3D_b = QtWidgets.QPushButton(self.groupBox_24)
        self.reconstruct_3D_b.setObjectName("reconstruct_3D_b")
        self.gridLayout_33.addWidget(self.reconstruct_3D_b, 2, 1, 1, 1)
        self.save_3D_track_cb = QtWidgets.QCheckBox(self.groupBox_24)
        self.save_3D_track_cb.setChecked(True)
        self.save_3D_track_cb.setObjectName("save_3D_track_cb")
        self.gridLayout_33.addWidget(self.save_3D_track_cb, 0, 1, 1, 1)
        self.tracks3D_LW = QtWidgets.QListWidget(self.groupBox_24)
        self.tracks3D_LW.setObjectName("tracks3D_LW")
        self.gridLayout_33.addWidget(self.tracks3D_LW, 1, 2, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_24, 1, 0, 1, 3)
        self.groupBox_16 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_16.setEnabled(False)
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.removelonersCheckBox_2 = QtWidgets.QCheckBox(self.groupBox_16)
        self.removelonersCheckBox_2.setObjectName("removelonersCheckBox_2")
        self.gridLayout_15.addWidget(self.removelonersCheckBox_2, 0, 0, 1, 1)
        self.rSTDCheckBox_2 = QtWidgets.QCheckBox(self.groupBox_16)
        self.rSTDCheckBox_2.setObjectName("rSTDCheckBox_2")
        self.gridLayout_15.addWidget(self.rSTDCheckBox_2, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_16)
        self.label_24.setObjectName("label_24")
        self.gridLayout_15.addWidget(self.label_24, 2, 0, 1, 1)
        self.rstd_periods_LineEdit_2 = QtWidgets.QLineEdit(self.groupBox_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rstd_periods_LineEdit_2.sizePolicy().hasHeightForWidth())
        self.rstd_periods_LineEdit_2.setSizePolicy(sizePolicy)
        self.rstd_periods_LineEdit_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rstd_periods_LineEdit_2.setObjectName("rstd_periods_LineEdit_2")
        self.gridLayout_15.addWidget(self.rstd_periods_LineEdit_2, 2, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_16)
        self.label_25.setObjectName("label_25")
        self.gridLayout_15.addWidget(self.label_25, 3, 0, 1, 1)
        self.rstd_threshold_LineEdit_2 = QtWidgets.QLineEdit(self.groupBox_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rstd_threshold_LineEdit_2.sizePolicy().hasHeightForWidth())
        self.rstd_threshold_LineEdit_2.setSizePolicy(sizePolicy)
        self.rstd_threshold_LineEdit_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rstd_threshold_LineEdit_2.setObjectName("rstd_threshold_LineEdit_2")
        self.gridLayout_15.addWidget(self.rstd_threshold_LineEdit_2, 3, 1, 1, 1)
        self.ppExecute_B = QtWidgets.QPushButton(self.groupBox_16)
        self.ppExecute_B.setObjectName("ppExecute_B")
        self.gridLayout_15.addWidget(self.ppExecute_B, 4, 0, 1, 2)
        self.gridLayout_10.addWidget(self.groupBox_16, 1, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.gridLayout_14.addWidget(self.groupBox_9, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_13.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.blockRegion_CB.clicked['bool'].connect(self.groupBox_21.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Chose project path:"))
        self.active_path_label.setText(_translate("MainWindow", "No path specified"))
        self.label_20.setText(_translate("MainWindow", "Active path:"))
        self.chooseProjectPath_b.setText(_translate("MainWindow", "Choose project path"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Load 3D calibration files:"))
        self.loadCal3D_b.setText(_translate("MainWindow", "Choose 3D calibrations for each camera view"))
        self.removeCal3D_b.setText(_translate("MainWindow", "Remove 3D calibrations"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Project"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Tracking output:"))
        self.groupBox_7.setToolTip(_translate("MainWindow", "Video loading functions"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Tracking:"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Track control:"))
        self.label_8.setText(_translate("MainWindow", "Tracks between frames :"))
        self.label_13.setText(_translate("MainWindow", "and"))
        self.start_l.setText(_translate("MainWindow", "0"))
        self.end_l.setText(_translate("MainWindow", "100"))
        self.trkTrack_B.setToolTip(_translate("MainWindow", "Starts object tracking on currently loaded video."))
        self.trkTrack_B.setText(_translate("MainWindow", "Track"))
        self.selectStartStop_b.setText(_translate("MainWindow", "Select tracking start and stop frames"))
        self.groupBox.setTitle(_translate("MainWindow", "Video parameters:"))
        self.trkPreview_B.setToolTip(_translate("MainWindow", "HI"))
        self.trkPreview_B.setText(_translate("MainWindow", "Fast Preview"))
        self.trkFramerate_LE.setToolTip(_translate("MainWindow", "set to 27 fps by default"))
        self.trkFramerate_LE.setText(_translate("MainWindow", "300"))
        self.trkFramerate_LE.setPlaceholderText(_translate("MainWindow", "Enter framerate"))
        self.label_7.setText(_translate("MainWindow", "fps"))
        self.label_2.setText(_translate("MainWindow", "Enter framerate:"))
        self.label_10.setText(_translate("MainWindow", "Video path:"))
        self.trkLoad_B.setText(_translate("MainWindow", "Load Video"))
        self.pathLabel.setText(_translate("MainWindow", "No video loaded"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Background subtraction method:"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Specify region"))
        self.le_originy.setToolTip(_translate("MainWindow", "pixel position in y from top left hand corner of frame"))
        self.le_originy.setText(_translate("MainWindow", "250"))
        self.le_originx.setToolTip(_translate("MainWindow", "pixel position in x from top left hand corner of frame"))
        self.le_originx.setText(_translate("MainWindow", "1280"))
        self.le_topx.setToolTip(_translate("MainWindow", "pixel position in x from top left hand corner of frame"))
        self.le_topx.setText(_translate("MainWindow", "0"))
        self.le_topy.setToolTip(_translate("MainWindow", "pixel position in x from top left hand corner of frame"))
        self.le_topy.setText(_translate("MainWindow", "275"))
        self.label_18.setToolTip(_translate("MainWindow", "pixel height of region"))
        self.label_18.setText(_translate("MainWindow", "top y"))
        self.label_19.setToolTip(_translate("MainWindow", "x origin of region (in pixels)"))
        self.label_19.setText(_translate("MainWindow", "bottom x"))
        self.label_21.setToolTip(_translate("MainWindow", "y origin of region (in pixels)"))
        self.label_21.setText(_translate("MainWindow", "bottom y"))
        self.label_11.setText(_translate("MainWindow", "top x"))
        self.rb_MOG.setText(_translate("MainWindow", "MOG background subtraction"))
        self.rb_absolute.setText(_translate("MainWindow", "Absolute difference"))
        self.blockRegion_CB.setText(_translate("MainWindow", "Block out region"))
        self.groupBox_2.setToolTip(_translate("MainWindow", "Lower limit for detectable contour area in pixels"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Live video treatment:"))
        self.medianFilterCheckbox.setToolTip(_translate("MainWindow", "Removes fuzzy noise (slow)"))
        self.medianFilterCheckbox.setText(_translate("MainWindow", "Apply median filter"))
        self.kernelSlider.setToolTip(_translate("MainWindow", "Choose kernel size for dilate and erode"))
        self.kernelValueLabel.setText(_translate("MainWindow", "0"))
        self.erodeCheckbox.setToolTip(_translate("MainWindow", "Useful to erode away noise"))
        self.erodeCheckbox.setText(_translate("MainWindow", "Erode"))
        self.dilateCheckbox.setToolTip(_translate("MainWindow", "Useful to increase size of small objects"))
        self.dilateCheckbox.setText(_translate("MainWindow", "Dilate"))
        self.contourLineEdit.setToolTip(_translate("MainWindow", "Default is 100"))
        self.contourLineEdit.setText(_translate("MainWindow", "100"))
        self.label_9.setText(_translate("MainWindow", "px"))
        self.label_5.setText(_translate("MainWindow", "px"))
        self.trkContour_B.setText(_translate("MainWindow", "Reset contour area limit"))
        self.gaussCheckBox.setToolTip(_translate("MainWindow", "Smooth out image"))
        self.gaussCheckBox.setText(_translate("MainWindow", "Use Guassian blur"))
        self.gaussSlider.setToolTip(_translate("MainWindow", "Reduce with noise with Gaussian filter"))
        self.gaussValueLabel.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "px"))
        self.medianValueLabel.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tracking"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Tableview:"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Post-processing"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Associate calibrations"))
        self.label_3.setText(_translate("MainWindow", "3D - associate calibrations:"))
        self.calView1_3D_select_B.setText(_translate("MainWindow", "View 1"))
        self.calView2_3D_select_B.setText(_translate("MainWindow", "View 2"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Manual false detection removal"))
        self.ppBlank_B.setToolTip(_translate("MainWindow", "Removed erroneous data from selected rows in the table."))
        self.ppBlank_B.setText(_translate("MainWindow", "Blank selected rows"))
        self.ppUndo_B.setToolTip(_translate("MainWindow", "Reverts active track back to its orginal state."))
        self.ppUndo_B.setText(_translate("MainWindow", "Undo changes to active file"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Import tracks and attribute calibrations:"))
        self.ppClearList_B.setToolTip(_translate("MainWindow", "Unload all previously loaded tracks"))
        self.ppClearList_B.setText(_translate("MainWindow", "Clear track list"))
        self.label_34.setText(_translate("MainWindow", "Calibrations:"))
        self.label_4.setText(_translate("MainWindow", "Please select track to edit:"))
        self.csvList_LW.setToolTip(_translate("MainWindow", "Selected item in list is the active file for post-processing. Make sure cameras appear in list in ascending order (i.e. first, second, third camera going upstream)."))
        self.show2Dplot_B.setText(_translate("MainWindow", "Show plot when selected"))
        self.ppFileOpen_B.setToolTip(_translate("MainWindow", "Select all file for post-processing a single trajectory."))
        self.ppFileOpen_B.setText(_translate("MainWindow", "Load tracks ..."))
        self.groupBox_24.setTitle(_translate("MainWindow", "3D reconstruction:"))
        self.addView_3D_b.setToolTip(_translate("MainWindow", "Add only one latLong track"))
        self.addView_3D_b.setText(_translate("MainWindow", "<- add view"))
        self.label_33.setText(_translate("MainWindow", "3D tracks:"))
        self.label_32.setText(_translate("MainWindow", "Tracks for reconstruction:"))
        self.clear_reconst3D_LW_b.setToolTip(_translate("MainWindow", "Clear tracks for reconstructions"))
        self.clear_reconst3D_LW_b.setText(_translate("MainWindow", "Clear"))
        self.cleartracks3DLW_b.setText(_translate("MainWindow", "Clear 3D tracks"))
        self.reconstruct_3D_b.setText(_translate("MainWindow", "Reconstruct 3D"))
        self.save_3D_track_cb.setText(_translate("MainWindow", "Automatically save 3D track to csv"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Automated false detection removal"))
        self.removelonersCheckBox_2.setText(_translate("MainWindow", "Remove lone values"))
        self.rSTDCheckBox_2.setText(_translate("MainWindow", "Perform rSTD removal"))
        self.label_24.setText(_translate("MainWindow", "rSTD periods"))
        self.label_25.setText(_translate("MainWindow", "rSTD threshold"))
        self.ppExecute_B.setText(_translate("MainWindow", "Process"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Processing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

